version: '3'
services:
  api:
    container_name: graphql-lab-api
    image: graphql-lab-api
    restart: always
    build: .
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    container_name: graphql-lab-mongo
    image: mongo:3.7
    restart: always
    tty: true
    hostname: graphql-lab-mongo
    ports:
      - '27017'
